/* This file was generated by syncqt. */
#ifndef QT_QTMQTT_VERSION_H
#define QT_QTMQTT_VERSION_H

#define QTMQTT_VERSION_STR "5.9.2"

#define QTMQTT_VERSION 0x050902

#endif // QT_QTMQTT_VERSION_H
